apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-management
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The root Argo CD project for cluster management. Everything else is deployed by this.

  # Allow only the infra repo to deploy stuff in this project; i.e. enforce
  # dedicated projects (with dedicated limits) for other projects.
  sourceRepos:
    - 'https://github.com/t-winter/infrastructure'

  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
