apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-management
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: The root Argo CD project for cluster management. Everything else is deployed by this.

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'https://github.com/t-winter/infrastructure'
