apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - namespace-argocd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v3.0.5/manifests/install.yaml
