apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: &namespace external-secrets
spec:
  project: cluster-management
  destination:
    server: "https://kubernetes.default.svc"
    namespace: *namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.19.2
    helm:
      valuesObject:
        grafanaDashboard:
          enabled: true
