apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: github
spec:
  provider:
    # provider type: github
    github:
      appID: 1862785
      # url: Default "https://github.com/", for enterprise Github instances uncomment and add your domain like "https://github.domain.com/"
      # uploadURL: Default "https://github.com"
      auth:
        privateKey:
          namespace: external-secrets
          name: github-app-private-key
          key: privateKey.pem
      # you can find this in the URL when configuring the app from the repo settings
      # the scheme should be https://github.com/settings/installations/<ID>
      installationID: 83377904
      organization: "t-winter"
      repository: "infrastructure"
      environment: "contabo3"