apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: external-secrets
  name: test
spec:
  secretStoreRef:
    name: github
    kind: ClusterSecretStore
  target:
    name: test
  data:
    - secretKey: test
      remoteRef:
       key: TEST_SECRET
